app/posts/forms.py
from wtforms import Form, SearchField, TextAreaField

class PostForm(Form):
    title = SearchField('Title')
    body = TextAreaField('Body')

app/posts/blueprint.py
from flask import Blueprint, render_template
from flask import render_template
from models import Post, Tag
from flask import request
from .forms import PostForm
from app import db
from flask import redirect
from flask import url_for
from flask_security import login_required


posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('db error')
        return redirect( url_for('posts.index') )
    form = PostForm()
    return render_template('posts/create_post.html', form=form)

@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)
    

@posts.route('/')
def index():
    q = request.args.get('q', '')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())
    pages = posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', pages=pages)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
<p class="text-center">
    New post
</p>    
{% endblock %}

{% block content %}
<div class="col-md-3"></div>
<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        
        {% for field in form %}      
            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-success btn-lg mt-2">Create</button>
    </form>
</div>
<div class="col-md-3"></div>
{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
<p class="text-center">
    Edit post
</p>    
{% endblock %}

{% block content %}
<div class="col-md-3"></div>
<div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug ) }}" method="POST">
        
        {% for field in form %}      
            <div class="form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-success btn-lg mt-2">Edit</button>
    
    </form>
</div>
<div class="col-md-3"></div>
{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    
    {% for post in pages.items %}

    <p>
        <a href="{{  url_for('posts.post_detail', slug=post.slug)}}">{{ post.title }}</a>
    </p>
    {% endfor %}

    <nav>
        <ul class="pagination">
          <li 
          {% if pages.has_prev %}
            class="page-item"
          {% else %}
            class="page-item disabled"
          {% endif %}
          >
          <a class="page-link" href="./?page={{ pages.prev_num }}">&laquo</a></li>
          {% for page in pages.iter_pages() %}
            <li  
            {% if page == pages.page %}
            class="page-item active"
            {% else %}
            class="page-item"
            {% endif %}
            >
                <a class="page-link" href="./?page={{ page }}"> {{ page }} </a>
            </li>
          {% endfor %}
          <li 
          {% if pages.has_next %}
            class="page-item"
          {% else %}
            class="page-item disabled"
          {% endif %}
          >
          <a class="page-link" href="./?page={{ pages.next_num }}">&raquo</a></li>
        </ul>
      </nav>
{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{  post.title  }}
{% endblock %}

{% block content_title %}
    {{  post.title  }}
    {% endblock %}
    
    {% block content %}
    <div class="tags">
        {% for tag in tags %}
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
            <span class="badge bg-info text-dark">{{ tag.name }}</span>
        </a>
        {% endfor %}
    </div>
    <p>
        {{  post.body  }}
    </p>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    
    {% for post in posts %}
    <div class="post">
        <p>
            <a href="{{  url_for('posts.post_detail', slug=post.slug)}}">{{ post.title }}</a>
        </p>
    </div>
    {% endfor %}
{% endblock %}